[tool.ruff]
# Enable auto-fixes on save
fix = true
# Line length
line-length = 88
# Target Python version
target-version = "py312"

# Enable all rules by default
select = ["E", "F", "I", "N", "W", "B", "C4", "UP", "PL", "RUF"]

# Ignore specific rules
ignore = [
    "E501",  # Line too long
    "PLR0913",  # Too many arguments
]

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"
# Indent with spaces, rather than tabs
indent-style = "space"
# Respect magic trailing commas
skip-magic-trailing-comma = false
# Like Black, respect magic trailing commas
line-ending = "auto" 